version: v2beta1
name: plugin-config

vars:
  PLUGIN_IMAGE: ghcr.io/philippart/vcluster-plugin:v0.1.1-alpha1
  SERVICE_CIDR: $(vcluster get service-cidr)
  GOPROXY: "https://repo.cci.nokia.net/gocenter,https://repo.cci.nokia.net/proxy-golang-org"

images:
  plugin:
    image: ${PLUGIN_IMAGE}
    dockerfile: ./Dockerfile.dev
    rebuildStrategy: ignoreContextChanges
    createPullSecret: true
    # skipPush: true
    buildArgs:
      HTTP_PROXY: ${HTTP_PROXY}
      NO_PROXY: ${NO_PROXY}
      GOPROXY: ${GOPROXY}
    kaniko:
      env:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
        GOPROXY: ${GOPROXY}
      pullSecret: devspace-pull-secrets
      additionalMounts:
      - mountPath: /kaniko/.docker/
        secret:
          name: devspace-pull-secrets
          items:
          - key: .dockerconfigjson
            path: config.json
      args:
      - --skip-tls-verify
      - --skip-tls-verify-pull
      # - --no-push
    
functions:
  install_go_dependencies: |-
    if [ ! -d "vendor" ]; then
      echo "Executing 'go mod vendor'..."
      go mod vendor
    fi
  install_crds: |-
     kubectl apply -f manifests/crds.yaml
 
pipelines:
  deploy: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all  
    # extend the default deploy pipeline
    install_go_dependencies
    install_crds

deployments:
  plugin:
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
        version: 0.11.1
      valuesFiles:
      - plugin.yaml
      values:
        plugin:
          crd-sync:
            image: ${PLUGIN_IMAGE}
        serviceCIDR: ${SERVICE_CIDR}
        serviceAccount:
          create: false
          name: default
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        syncer:
          readinessProbe:
            enabled: false
          livenessProbe:
            enabled: false

dev:
  plugin:
    imageSelector: ${PLUGIN_IMAGE}
    terminal:
      command: "./devspace_start.sh"
    ports:
    - port: "2346:2345"
    sync:
    - path: ./:/vcluster
      uploadExcludePaths: [".git/"]

commands:
  # arguments: namespace
  pull-secret: |-
    kubectl create secret generic ghcr-secret \
    --from-file=.dockerconfigjson=../.docker/config.json \
    --type=kubernetes.io/dockerconfigjson \
    --namespace $1