version: v2beta1
name: plugin-config

vars:
  PLUGIN_IMAGE: ghcr.io/philippart/vcluster-plugin:latest
  SERVICE_CIDR: $(vcluster get service-cidr)

images:
  vcluster:
    image: ${PLUGIN_IMAGE}
    dockerfile: ./Dockerfile.dev
    rebuildStrategy: ignoreContextChanges
    createPullSecret: true
    skipPush: true
    buildArgs:
      HTTP_PROXY: ${HTTP_PROXY}
      NO_PROXY: ${HTTP_PROXY}

pipelines:
  # extend the default deploy pipeline
  deploy: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all  
    # Install dependencies
    if [ ! -d "vendor" ]; then
      echo "Executing 'go mod vendor'..."
      go mod vendor
    fi
    # Install car crd
    kubectl apply -f manifests/crds.yaml

deployments:
  vcluster:
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
        version: 0.11.1
      valuesFiles:
      - plugin.yaml
      values:
        plugin:
          crd-sync:
            image: ${PLUGIN_IMAGE}
        serviceCIDR: ${SERVICE_CIDR}
        serviceAccount:
          create: false
          name: default
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        syncer:
          readinessProbe:
            enabled: false
          livenessProbe:
            enabled: false

dev:
  plugin:
    imageSelector: ${PLUGIN_IMAGE}
    terminal:
      command: "./devspace_start.sh"
    ports:
    - port: "2346:2345"
    sync:
    - path: ./

commands:
  # arguments: secret name and namespace
  image-pull-secret: |-
    kubectl create secret generic $1 \
    --from-file=.dockerconfigjson=../.docker/config.json \
    --type=kubernetes.io/dockerconfigjson \
    --namespace $2