FROM golang:1.19 as builder

WORKDIR /vcluster

# Add labels
LABEL org.opencontainers.image.source=https://github.com/philippart/vcluster-plugin
LABEL org.opencontainers.image.description="vcluster plugin dev image"
LABEL org.opencontainers.image.licenses=Apache-2.0

# proxy env (passed via arg)
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTP_PROXY
ENV NO_PROXY=$NO_PROXY
ENV GOPROXY=$GOPROXY

# Install Delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ENV GO111MODULE on
ENV DEBUG true

ENTRYPOINT ["sleep", "999999999999"]