apiVersion: v1
kind: Service
metadata:
  name: plugin-nodeport
  namespace: vcdev
spec:
  selector:
    app: vcluster
    release: plugin
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort